### ISSUE TITLE
RuntimeException: Error receiving broadcast Intent

### ISSUE THREAD

**Issue by alishari** [aykuttasil/CallRecorder#11]
This problem happened in a Galaxy A3(2017) with 6.0.1 android:

Exception java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.PHONE_STATE flg=0x10 bqHint=4 VirtualScreenParam=Params{mDisplayId=-1, null, mFlags=0x00000000)} (has extras) } in com.aykuttasil.callrecord.b.a@ed6a8cf
android.app.LoadedApk$ReceiverDispatcher$Args.run (LoadedApk.java:1007)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:7407)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
arrow_drop_down
Caused by java.lang.IllegalStateException:
android.media.MediaRecorder._stop (MediaRecorder.java)
android.media.MediaRecorder.stop (MediaRecorder.java:973)
com.aykuttasil.callrecord.receiver.CallRecordReceiver.onIncomingCallReceived (CallRecordReceiver.java)
<OR>.onIncomingCallEnded (CallRecordReceiver.java)
<OR>.onRecordingStarted (CallRecordReceiver.java)
<OR>.stopRecord (CallRecordReceiver.java)
com.aykuttasil.callrecord.receiver.CallRecordReceiver.onIncomingCallReceived (CallRecordReceiver.java)
<OR>.onIncomingCallEnded (CallRecordReceiver.java)
<OR>.onRecordingStarted (CallRecordReceiver.java)
<OR>.stopRecord (CallRecordReceiver.java)
com.aykuttasil.callrecord.receiver.PhoneCallReceiver.onIncomingCallReceived (PhoneCallReceiver.java)
<OR>.onIncomingCallEnded (PhoneCallReceiver.java)
<OR>.onCallStateChanged (PhoneCallReceiver.java)
com.aykuttasil.callrecord.receiver.PhoneCallReceiver.onReceive (PhoneCallReceiver.java)
android.app.LoadedApk$ReceiverDispatcher$Args.run (LoadedApk.java:997)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:7407)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)

**Comment by BhargavVGhodasara** [comment]
Hey, @alishari 

 I have also same issue on Redmi 4(6.0.1).

`
01-02 16:17:49.115 15825-15825/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: recorder.com.callrecord, PID: 15825
                                                   java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.PHONE_STATE flg=0x10 (has extras) } in com.aykuttasil.callrecord.receiver.CallRecordReceiver@a50a064
                                                       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:893)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
                                                    Caused by: java.lang.RuntimeException: start failed.
                                                       at android.media.MediaRecorder.start(Native Method)
                                                       at com.aykuttasil.callrecord.receiver.CallRecordReceiver.startRecord(CallRecordReceiver.java:162)
                                                       at com.aykuttasil.callrecord.receiver.CallRecordReceiver.onOutgoingCallStarted(CallRecordReceiver.java:52)
                                                       at com.aykuttasil.callrecord.receiver.PhoneCallReceiver.onCallStateChanged(PhoneCallReceiver.java:82)
                                                       at com.aykuttasil.callrecord.receiver.PhoneCallReceiver.onReceive(PhoneCallReceiver.java:41)
                                                       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:883)
                                                       at android.os.Handler.handleCallback(Handler.java:739) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5441) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628) `

**Comment by mohit-sharma-87** [comment]
Any update on this issue ?
