### ISSUE TITLE
Runtime Exception

### ISSUE THREAD

**Issue by rayalakiran** [aykuttasil/CallRecorder#42]
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.aykuttasil.callrecorder/com.aykuttasil.callrecorder.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.aykuttasil.callrecorder.MainActivity" on path: DexPathList[[zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/base.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_dependencies_apk.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_resources_apk.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_slice_0_apk.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_slice_1_apk.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_slice_2_apk.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_slice_3_apk.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_slice_4_apk.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_slice_5_apk.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_slice_6_apk.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_slice_7_apk.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_slice_8_apk.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/lib/arm, /system/lib, /system/vendor/lib]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2762)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.aykuttasil.callrecorder.MainActivity" on path: DexPathList[[zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/base.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_dependencies_apk.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_resources_apk.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_slice_0_apk.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_slice_1_apk.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_slice_2_apk.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_slice_3_apk.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_slice_4_apk.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_slice_5_apk.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_slice_6_apk.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_slice_7_apk.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_slice_8_apk.apk", zip file "/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.aykuttasil.callrecorder-M9U6w5G5IjrGVnLni65F1w==/lib/arm, /system/lib, /system/vendor/lib]]
2019-03-04 12:59:43.557 20806-20806/? E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)

**Comment by abrarShariar** [comment]
Did you find any solution @rayalakiran. I am also facing similar issue.

**Comment by bosir** [comment]
I also have this problem

**Comment by CListery** [comment]
@abrarShariar @bosir 
You need to add in build.gradle 

> apply plugin: 'kotlin-android'

**Comment by mrubinodevelop** [comment]
very good
